server:
  port: 58080

spring:
  application:
    name: clarity-b2b-product-endpoint

liferay:
  url: ${PORTAL_URL:http://localhost:8080}
  channel:
    id: ${LIFERAY_CHANNEL_ID:97521}
  admin:
    email: ${LIFERAY_ADMIN_EMAIL_ADDRESS:ian.miller@clarityvisionsolutions.com}
    password: ${LIFERAY_ADMIN_PASSWORD:learn}
